import hunspell
h = hunspell.HunSpell('/opt/pt_BR.dic', '/opt/pt_BR.aff')
h.spell('menino')
h.spell('menin')
h.suggest('menin')
h.suggest('meninu')
h.suggest('menini')
h.suggest('meninus')
h.suggest('uva')
h.suggest('vau')
h.suggest('vaux')
h.suggest("vau")
h.suggest("meninu")
h.suggest("meninus")
h.suggest("minino")
h.suggest("minino")
h.suggest("minino")
h.suggest("minino")
h.stem('meninos')
h.stem('meninas')
h.stem('inconstitucional')
h.stem('amargura')
h.stem('menininho')
h.stem('menininhas')
h.stem('impressora')
h.stem('carregadores')
h.stem('menininho comendo rapadura')

